In [3]:
import pandas as pd
import numpy as np

In [4]:
tasks_df = pd.read_csv("tasks.csv")
users_df = pd.read_csv("users.csv")

In [5]:
tasks_df.head()

,id,title,description,create_time,status,assignee_id,priority,due_time
0,1,رفع باگ ورود کاربران,بررسی و رفع خطای لاگین در نسخه وب,2026/01/05,Done,1,High,2026/01/08
1,2,پیاده سازی API احراز هویت,ایجاد سرویس JWT برای کاربران,2026/01/07,Done,2,Critical,2026/01/15
2,3,طراحی داشبورد مدیریت,طراحی اولیه داشبورد مدیران سیستم,2026/01/10,In Progress,3,High,2026/06/15
3,4,تهیه گزارش مالی دی ماه,آماده سازی گزارش هزینه های ماهانه,2026/01/12,Done,7,Medium,2026/01/20
4,5,پاسخگویی به تیکت های مشتریان,بررسی تیکت های معوق,2026/01/15,Done,5,Medium,2026/01/18

In [6]:
users_df.head()

   id    fullname department
0   1   علی صابری        فنی
1   2   رضا محمدی        فنی
2   3  سارا احمدی      محصول
3   4  محمد رضایی     مدیریت
4   5  مریم کریمی   پشتیبانی

In [11]:
users_df = users_df.set_index("id")
tasks_df["fullname"] = tasks_df["assignee_id"].map(users_df["fullname"])
tasks_df["department"] = tasks_df["assignee_id"].map(users_df["department"])

In [12]:
tasks_df.head()

,id,title,description,create_time,status,assignee_id,priority,due_time,fullname,department
0,1,رفع باگ ورود کاربران,بررسی و رفع خطای لاگین در نسخه وب,2026/01/05,Done,1,High,2026/01/08,علی صابری,فنی
1,2,پیاده سازی API احراز هویت,ایجاد سرویس JWT برای کاربران,2026/01/07,Done,2,Critical,2026/01/15,رضا محمدی,فنی
2,3,طراحی داشبورد مدیریت,طراحی اولیه داشبورد مدیران سیستم,2026/01/10,In Progress,3,High,2026/06/15,سارا احمدی,محصول
3,4,تهیه گزارش مالی دی ماه,آماده سازی گزارش هزینه های ماهانه,2026/01/12,Done,7,Medium,2026/01/20,نرگس حسینی,مالی
4,5,پاسخگویی به تیکت های مشتریان,بررسی تیکت های معوق,2026/01/15,Done,5,Medium,2026/01/18,مریم کریمی,پشتیبانی